baseurl = "http://blog.awm.jp/"
languageCode = "ja-JP"
theme = "base16"
title = "awm-Tech"
copyright = "&copy; awm.jp"
disqusShortname = "awmtech"
hasCJKLanguage = true
paginate = 5

[params]

author = "awmlabs"
avatar = "https://avatars3.githubusercontent.com/u/12230940?v=3&s=400"
contact = "labs@g.awm.jp"
