baseurl: "http://blog.awm.jp/"
languageCode: "jp-JP"
theme: "base16"
title: "awm TechNotes"
copyright: "&copy; awm.jp"
disqusShortname: "awmnotes"

params:
  author: "awmlabs"
  avatar: "https://avatars3.githubusercontent.com/u/12230940?v=3&s=400"
  contact: "labs@g.awm.jp"
